---
job: extension
config:
  name: "flex_lora"
  process:
    - type: "sd_trainer"
      training_folder: "output"
      device: cuda:0
      trigger_word: "p3r5onTr1g"

      network:
        type: "lora"
        linear: 16
        linear_alpha: 16
        # linear_alpha: if > than linear, faster convergence, LoRA contribution stronger.
        # try 16-20 or 16-24, with less steps

      save:
        dtype: float32
        save_every: 2600
        max_step_saves_to_keep: 1
        push_to_hub: false

      datasets:
        - folder_path: "dataset"
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [768, 1024, 1536] # just 1024

      train:
        batch_size: 1
        steps: 2600
        gradient_accumulation: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adamw"
        lr: 1e-4
        skip_first_sample: true
        disable_sampling: true
        linear_timesteps: true

        ema_config:
          use_ema: true
          ema_decay: 0.995

        dtype: bf16

      model:
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        quantize: false

meta:
  name: "[name]"
  version: "1.0"
