---
job: extension
config:
  name: "flex_lora_sup"
  process:
    - type: "sd_trainer"
      training_folder: "output"
      device: cuda:0
      trigger_word: "p3r5onTr1g"

      network:
        type: "lora"
        linear: 16
        linear_alpha: 16

      save:
        dtype: float32
        save_every: 100
        max_step_saves_to_keep: 5
        push_to_hub: false

      datasets:
        - folder_path: "dataset"
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [1024, 1536]

      train:
        batch_size: 1
        steps: 2400
        gradient_accumulation: 1
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adamw"
        lr: 1e-4
        skip_first_sample: true
        # disable_sampling: true
        # linear_timesteps: true

        ema_config:
          use_ema: true
          ema_decay: 0.995

        dtype: fp32

      model:
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        quantize: false
        transformer_only: false

      sample:
        sampler: "flowmatch"
        sample_every: 100
        width: 1024
        height: 1024
        prompts:
          - "[trigger], playing chess at the park, bomb going off in the background"
          - "[trigger] holding a coffee cup, in a beanie, sitting at a cafe"
          - "[trigger] is a DJ at a night club, fish eye lens, smoke machine, lazer lights, holding a martini"
          - "[trigger] playing the guitar, on stage, singing a song, laser lights, punk rocker"
          - "photo of [trigger], white background, medium shot, modeling clothing, studio lighting, white backdrop"
        neg: ""
        seed: 42
        walk_seed: true
        guidance_scale: 4
        sample_steps: 20

meta:
  name: "[name]"
  version: "1.0"
